### ISSUE TITLE
issues to run in ubuntu 20.04 - Openjdk 8

### ISSUE THREAD

**Issue by leonbravo** [AgenciaImplementacion/iliSuite#9]
java -jar --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml,javafx.graphics /home/leono/Downloads/iliSuite_bin-1.3.4/iliSuite-1.3.4.jar
Exception in thread "main" java.lang.IllegalAccessError: class ai.ilisuite.application.MainPreLoad (in unnamed module @0x5197848c) cannot access class com.sun.javafx.application.LauncherImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to unnamed module @0x5197848c
    at ai.ilisuite.application.MainPreLoad.main(MainPreLoad.java:7)

**Comment by yesidpol** [comment]
I just uploaded [iliSuite binaries for linux and Java 11](https://github.com/SwissTierrasColombia/iliSuite/releases/tag/v1.3.4). I updated to Java 11 because openjdk 8 doesn't have default support anymore in Ubuntu 20.04. It's not necessary to add module-path argument, just execute ```java -jar iliSuite-1.3.4.jar```

**Comment by leonbravo** [comment]
Gracias

Siguiendo la instalacion me encuentro con que no es posible continuar, de
las opciones disponibles asumo que no logra traer modelos o archivos ili?

Ver imagenes adjuntas


[image: image.png]


[image: image.png]

Me pueden informar que hacer en este caso?


Regards,



*Leonardo Bravo *

**Comment by leonbravo** [comment]
Estimado Yesid,

Tambien se deberia actualizar el uso de javafx

Actualmente  java openjdk  no la encuentra sin parámetros extra


java -jar iliSuite-1.3.4.jar
Exception in thread "main" java.lang.NoClassDefFoundError:
javafx/application/Application
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
at
java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
at
java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
at
java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at ai.ilisuite.application.MainPreLoad.main(MainPreLoad.java:7)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)


Warm Regards,



*Leonardo Bravo *
Data Engineer and Information Consultant
Project Manager Professional   -  Scrum Master  Agile Institute

Mob +61 481 811 308  | Skype   leon.bravo.marroquin | Brisbane 4000
